easy_admin:
    site_name: 'Linio Books'
    entities:
        ApiVendor:
            label: 'Api Vendor'
            class: AppBundle\Entity\ApiVendor
        User:
            label: 'Usuarios'
            class: AppBundle\Entity\User