old_sound_rabbit_mq:
    connections:
        default:
            host:     %rabbit_host%
            port:     %rabbit_port%
            user:     %rabbit_user%
            password: %rabbit_password%
            vhost:    '/'
            lazy:     false
            connection_timeout: 3
            read_write_timeout: 3

            # requires php-amqplib v2.4.1+ and PHP5.4+
            keepalive: false

            # requires php-amqplib v2.4.1+
            heartbeat: 0
    producers:
        push_file:
            connection:       default
            exchange_options: {name: 'push-file', type: direct}
            queue_options: { name: 'push-file'}
#    consumers:
#        upload_picture:
#            connection:       default
#            exchange_options: {name: 'upload-picture', type: direct}
#            queue_options:    {name: 'upload-picture'}
#            callback:         upload_picture_service