# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    api.search:
        class: AppBundle\Service\SearchService
        arguments: ["@api.adapter.factory"]

    api.adapter.factory:
        class: AppBundle\Factory\AdapterFactory

    bookslookup.queue:
        class: AppBundle\Service\ProducerService
        arguments: ["@old_sound_rabbit_mq.push_file_producer"]
